### ISSUE TITLE
allow specifying compression quality

### ISSUE THREAD

**Issue by maxjvh** [httptoolkit/brotli-wasm#2]
very useful module already! but it would be even greater if `compress()` took an additional parameter for specifying the compression quality.

i'm compressing a huge JSON object and since Brotli apparently defaults to the absolute highest quality setting, the compression is taking over 5 seconds.

**Comment by pimterry** [comment]
Good suggestion! Yes, I agree, that would be very useful. If you have time to investigate how to make that work, I'd happily accept a PR for this.

I'd suggest including it as a general-purpose optional parameters object, just including quality for now, so that it could be extended later to more of the [available parameters](https://github.com/dropbox/rust-brotli/blob/458f5780a37674c3bae38212e11166b22d3198b1/corrosion/backward_references_hq.rs#L184-L195).

**Comment by maxjvh** [comment]
hey @pimterry! opened a PR: #3
