### ISSUE TITLE
Does not work in rollup

### ISSUE THREAD

**Issue by TJKoury** [httptoolkit/brotli-wasm#4]
Rollup has issues with the wasm-bindgen implementation, does not recognize methods / properties attached to wasm object.

Recommend recompiling using `--target web`;

**Comment by pimterry** [comment]
Interesting! Yes, it seems that rollup doesn't support [WASM ESM integration](https://github.com/WebAssembly/esm-integration), which is required for the bundler target. There's maybe some progress happening there (https://github.com/rollup/rollup/issues/2099) but very slowly.

If you're keen, I'm open to PRs to support this, if you can find a way to do so that's still compatible with the node & webpack builds as well (if the current tests still pass, that should be enough). I'm not sure exactly how the various package.json fields should be set to support all three targets easily. 

Super extra bonus points if you can add a separate test to cover rollup too, so we can make sure this works in future.

**Comment by pimterry** [comment]
Now fixed by #13 in version v1.3.0.
